name: housing_ml_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.11.2
  - pyyaml=6.0
  - requests=2.31.0
  - tqdm=4.66.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.18.0
  - jupyter=1.0.0
  - ipykernel=6.25.2
