name: housing_ml_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - torchvision=0.16.0
  - scikit-learn=1.3.1
  - xgboost=2.0.0
  - catboost=1.2.2
