apiVersion: v1
kind: Service
metadata:
  name: cloudeasyml
  namespace: ml-platform
spec:
  selector:
    app: cloudeasyml
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
